image:
  repository: ghcr.io/openclaw/openclaw
  tag: latest

agent:
  model: google/gemini-3-flash-preview

persistence:
  size: 5Gi

ingress:
  enabled: false
  match: ""

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi

secrets:
  gatewayToken: ""
  anthropicApiKey: ""
  geminiApiKey: ""
  telegramBotToken: ""
  githubToken: ""
