apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-google-clive
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  client-id: {{ .Values.secrets.googleCliveClientId | quote }}
  client-secret: {{ .Values.secrets.googleCliveClientSecret | quote }}
  refresh-token: {{ .Values.secrets.googleCliveRefreshToken | quote }}
