apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  gateway-token: {{ .Values.secrets.gatewayToken | quote }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | quote }}
  gemini-api-key: {{ .Values.secrets.geminiApiKey | quote }}
  telegram-bot-token: {{ .Values.secrets.telegramBotToken | quote }}
  google-clive-client-id: {{ .Values.secrets.googleCliveClientId | quote }}
  google-clive-client-secret: {{ .Values.secrets.googleCliveClientSecret | quote }}
  google-clive-refresh-token: {{ .Values.secrets.googleCliveRefreshToken | quote }}
