{{- range $name, $route := .Values.ingressRoutes }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $name }}
  namespace: {{ $route.namespace }}
spec:
  entryPoints:
    - web
  routes:
  - match: {{ $route.match | quote }}
    kind: Rule
    services:
    - name: {{ $route.service.name }}
      {{- if $route.service.namespace }}
      namespace: {{ $route.service.namespace }}
      {{- end }}
      port: {{ $route.service.port }}
    {{- if $route.middlewares }}
    middlewares:
    {{- range $route.middlewares }}
    - name: {{ . }}
      namespace: {{ $route.namespace }}
    {{- end }}
    {{- end }}
{{- end }}
